spring:
  datasource:
    username: root
    password: a+rquQe5KMGKKkmFJkl0
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    url: jdbc:mysql://192.168.0.248/jifen?useUnicode=true&characterEncoding=UTF-8
    minIdle: 5
    maxActive: 20


  redis:
    host: 192.168.0.248
    port: 10000
    password: acGrfP9omb1EGMzCUazC
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
    timeout: 5000
    database: 0

  application:
    name: bootj-service

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZonehttp: http://localhost:8761/eureka/

management:
  security:
    enabled: false





