server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
#      label: master
      server:
        git:
          uri: https://github.com/thythm/SpringcloudConfig/
          search-paths: /data

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

management:
  security:
    enabled: false

